export const SELECTED_BUCKET = "SELECTED_BUCKET";
export const CLEAR_BUCKET_SELECTED = "CLEAR_BUCKET_SELECTED";
export const SELECTED_COMBO = "SELECTED_COMBO";
export const CLEAR_COMBO_SELECTED = "CLEAR_COMBO_SELECTED";