export const allIndentsInit = {
    indentsList:[
        {
            storeName:"乐百氏旗舰店",
            productList:[
                {
                    productName:'乐百氏  矿泉水',
                    pic:'src/images/goods_ticket_bg.png',
                    volume:'18.9L',
                    sale:'23.00',
                    number:'1',
                },
            ],
            condition:'待付款',
            waitReturn:false,
            payment:true,
            delivery:false,
            evaluate:false,
            complete:false,
            saleReturn:false
        },
        {
            storeName:"乐百氏旗舰店",
            productList:[
                {
                    productName:'乐百氏  矿泉水',
                    pic:'src/images/goods_ticket_bg.png',
                    volume:'18.9L',
                    sale:'23.00',
                    number:'1',
                },
            ],
            condition:'待评价',
            waitReturn:false,
            payment:false,
            delivery:false,
            evaluate:true,
            complete:false,
            saleReturn:false
        },
        {
            storeName:"自营",
            productList:[
                {
                    productName:'喜腾山泉 天然饮用水',
                    pic:'src/images/goods_ticket_bg.png',
                    volume:'18L',
                    sale:'22.00',
                    number:'1',
                },
                {
                    productName:'喜腾山泉 天然饮用水 水票',
                    pic:'src/images/goods_ticket_bg.png',
                    volume:'18L',
                    sale:'22.00',
                    number:'1',
                },
            ],
            condition:'待收货',
            waitReturn:false,
            payment:false,
            delivery:true,
            evaluate:false,
            complete:false,
            saleReturn:false
        },
        {
            storeName:"乐百氏旗舰店",
            productList:[
                {
                    productName:'乐百氏  矿泉水',
                    pic:'src/images/goods_ticket_bg.png',
                    volume:'18.9L',
                    sale:'23.00',
                    number:'1',
                },
            ],
            condition:'完成',
            waitReturn:false,
            payment:false,
            delivery:false,
            evaluate:false,
            complete:true,
            saleReturn:false
        },
        {
            storeName:"自营",
            productList:[
                {
                    productName:'喜腾山泉 天然饮用水',
                    pic:'src/images/goods_ticket_bg.png',
                    volume:'18L',
                    sale:'22.00',
                    number:'1',
                },
                {
                    productName:'喜腾山泉 天然饮用水 水票',
                    pic:'src/images/goods_ticket_bg.png',
                    volume:'18L',
                    sale:'22.00',
                    number:'1',
                },
            ],
            condition:'已退货',
            waitReturn:false,
            payment:false,
            delivery:false,
            evaluate:false,
            complete:false,
            saleReturn:true
        }
    ]
};