export const stationInit ={
    stationList:[
        {
            pic:"",
            title:"生命之源水站",
            evaluate:4,
            sale:"1930",
            approve:true,
            approveImg:'src/images/common_lable_self-suport.png',
            address:"西城区百万庄大街2号甲"
        },
        {
            pic:"",
            title:"乐百氏旗舰店",
            evaluate:5,
            sale:"2396",
            approve:true,
            approveImg:'',
            address:"西城区车公庄北里6号楼"
        },
        {
            pic:"",
            title:"木樨地雀巢旗舰店",
            evaluate:5,
            sale:"1954",
            approve:true,
            approveImg:'',
            address:"西城区五路通街人定湖西里"
        },
        {
            pic:"",
            title:"普利思水站",
            evaluate:3,
            sale:"1396",
            approve:false,
            approveImg:'',
            address:"西城区德胜门内羊房18号"
        },
    ]
}